name: Auto Tag

on:
  push:
    branches:
      - main
    paths:
      - "package.json"

jobs:
  auto-tag:
    uses: tensakulabs/.github/.github/workflows/auto-tag.yml@main
    with:
      version_file: package.json
    permissions:
      contents: write
